project:
  type: website
  output-dir: docs
website:
  title: "Inger Bergom, PhD"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Music"
        href: music.qmd
format:
  html:
    theme: cosmo
    css: styles.css




