project:
  type: website
  output-dir: docs
website:
  title: "My Quarto Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
format:
  html:
    theme: cosmo
    css: styles.css

