---
format: 
  html:
    toc: true
editor: visual
execute:
  warning: false
---

Welcome to my website!

(It's a work in progress.)



I'm a higher ed researcher and enthusiast: I love the transformative power of higher education--transforming knowledge, careers, thinking, knowledge, and the world. I also love to study how it all works: how we create environments, communities, and processes that help people become their best selves through higher education. 

I *also* love building and creating things. Earlier in my life, this manifested in writing music. Now, I've learned that I can build and create with data! What I mean by that is this: building and creating tools, systems, and visualizations that help people make sense of lots of information. Turns out that music composition shares a lot in common with building data tools: both are about creating order from chaos and generating a product that inspires transformation.

Today I feel lucky that I can merge my research background with my creative side. I use my knowledge of higher education and research methods to understand what's happening at a university, then I build something that helps other people make sense of it, too. That "something" could be a written report, interactive dashboard, data visualization, an app, or whatever! I get excited thinking about the creative possibilities for generating and delivering a meaningful product for people to use. And, just like with music composition, I am motivated by the endless learning opportunities along the way to creating something beautiful.



